// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/login.tsx";
import * as $4 from "./routes/member/comfirmation.tsx";
import * as $5 from "./routes/member/completion.tsx";
import * as $6 from "./routes/member/registration.tsx";
import * as $7 from "./routes/mypage/application-history.tsx";
import * as $8 from "./routes/mypage/application.tsx";
import * as $9 from "./routes/mypage/browsing-history.tsx";
import * as $10 from "./routes/mypage/contract.tsx";
import * as $11 from "./routes/mypage/favorite-brand.tsx";
import * as $12 from "./routes/mypage/top.tsx";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/joke.ts": $1,
    "./routes/index.tsx": $2,
    "./routes/login.tsx": $3,
    "./routes/member/comfirmation.tsx": $4,
    "./routes/member/completion.tsx": $5,
    "./routes/member/registration.tsx": $6,
    "./routes/mypage/application-history.tsx": $7,
    "./routes/mypage/application.tsx": $8,
    "./routes/mypage/browsing-history.tsx": $9,
    "./routes/mypage/contract.tsx": $10,
    "./routes/mypage/favorite-brand.tsx": $11,
    "./routes/mypage/top.tsx": $12,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
