// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/brand/application/completion.tsx";
import * as $3 from "./routes/brand/application/confirmation.tsx";
import * as $4 from "./routes/brand/brand-detail.tsx";
import * as $5 from "./routes/brand/cancel-contract/completion.tsx";
import * as $6 from "./routes/brand/cancel-contract/confirmation.tsx";
import * as $7 from "./routes/brand/cancel/completion.tsx";
import * as $8 from "./routes/brand/cancel/confirmation.tsx";
import * as $9 from "./routes/brand/contract/completion.tsx";
import * as $10 from "./routes/brand/contract/confirmation.tsx";
import * as $11 from "./routes/freeword.tsx";
import * as $12 from "./routes/index.tsx";
import * as $13 from "./routes/login.tsx";
import * as $14 from "./routes/mypage/application-history.tsx";
import * as $15 from "./routes/mypage/applying.tsx";
import * as $16 from "./routes/mypage/browsing-history.tsx";
import * as $17 from "./routes/mypage/favorite.tsx";
import * as $18 from "./routes/mypage/index.tsx";
import * as $19 from "./routes/mypage/under-contract.tsx";
import * as $20 from "./routes/registration/completion.tsx";
import * as $21 from "./routes/registration/confirmation-company.tsx";
import * as $22 from "./routes/registration/confirmation.tsx";
import * as $23 from "./routes/registration/input.tsx";
import * as $24 from "./routes/search-genre.tsx";
import * as $$0 from "./islands/ApplicationHistory.tsx";
import * as $$1 from "./islands/Applying.tsx";
import * as $$2 from "./islands/BrandDetail.tsx";
import * as $$3 from "./islands/BrandPhoto.tsx";
import * as $$4 from "./islands/BrowsingHistory.tsx";
import * as $$5 from "./islands/Favorite.tsx";
import * as $$6 from "./islands/FavoriteBrands.tsx";
import * as $$7 from "./islands/Feature.tsx";
import * as $$8 from "./islands/Freeword.tsx";
import * as $$9 from "./islands/Login.tsx";
import * as $$10 from "./islands/RegistrationInput.tsx";
import * as $$11 from "./islands/SearchGenre.tsx";
import * as $$12 from "./islands/UnderContract.tsx";
import * as $$13 from "./islands/index.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/joke.ts": $1,
    "./routes/brand/application/completion.tsx": $2,
    "./routes/brand/application/confirmation.tsx": $3,
    "./routes/brand/brand-detail.tsx": $4,
    "./routes/brand/cancel-contract/completion.tsx": $5,
    "./routes/brand/cancel-contract/confirmation.tsx": $6,
    "./routes/brand/cancel/completion.tsx": $7,
    "./routes/brand/cancel/confirmation.tsx": $8,
    "./routes/brand/contract/completion.tsx": $9,
    "./routes/brand/contract/confirmation.tsx": $10,
    "./routes/freeword.tsx": $11,
    "./routes/index.tsx": $12,
    "./routes/login.tsx": $13,
    "./routes/mypage/application-history.tsx": $14,
    "./routes/mypage/applying.tsx": $15,
    "./routes/mypage/browsing-history.tsx": $16,
    "./routes/mypage/favorite.tsx": $17,
    "./routes/mypage/index.tsx": $18,
    "./routes/mypage/under-contract.tsx": $19,
    "./routes/registration/completion.tsx": $20,
    "./routes/registration/confirmation-company.tsx": $21,
    "./routes/registration/confirmation.tsx": $22,
    "./routes/registration/input.tsx": $23,
    "./routes/search-genre.tsx": $24,
  },
  islands: {
    "./islands/ApplicationHistory.tsx": $$0,
    "./islands/Applying.tsx": $$1,
    "./islands/BrandDetail.tsx": $$2,
    "./islands/BrandPhoto.tsx": $$3,
    "./islands/BrowsingHistory.tsx": $$4,
    "./islands/Favorite.tsx": $$5,
    "./islands/FavoriteBrands.tsx": $$6,
    "./islands/Feature.tsx": $$7,
    "./islands/Freeword.tsx": $$8,
    "./islands/Login.tsx": $$9,
    "./islands/RegistrationInput.tsx": $$10,
    "./islands/SearchGenre.tsx": $$11,
    "./islands/UnderContract.tsx": $$12,
    "./islands/index.tsx": $$13,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
